- Makefile
It was accidentally committed.
> Remove -x option to bash in SHELL

- cmd/manager/main.go
- deploy/prometheus-k8s-role.yaml
- deploy/prometheus-k8s-rolebinding.yaml
- pkg/metrics/metrics.go
- pkg/metrics/service.go
This PR ensures that when the operator is deployed, all the proper objects are placed so prometheus can scrape the custom metrics.
-The operator creates an deadmanssnitch-operator service to expose the metrics over on deploy
-The operator creates an deadmanssnitch-operator servicemonitor to tell prometheus how to digest the metrics
-Removes the operator-sdk metrics service for now
-Includes a prometheus-k8s role for the deadmanssnitch-operator namespace that has permissions to get, list and watch services, pods and endpoints.
-Includes a prometheus-k8s rolebinding to allow the prometheus-k8s serviceaccount from the openshift-monitoring namespace to use the aformentioned role.
When the operator and the role/rolebindings are deployed, the deadmanssnitch-operator namespace must be given the …
> Deploy needed objects for prometheus metrics when the operator comes up

- README.md
- deploy/prometheus-k8s-rules.yaml
In a previous PR, the metric was exposed without a corresponding alert. This PR adds an alert to fire when the API is unreachable for 15 minutes.
> Adding Prometheus Rule for Dead Man's Snitch API Call

- cmd/manager/main.go
- deploy/role.yaml
- pkg/metrics/service.go
This PR updates the local metrics package to the latest method. It also replaces the creation of a ServiceMonitor with a Route to enable external scraping.
For reference, the metrics pkg code already exists in the aws-account-operator: https://github.com/openshift/aws-account-operator/blob/master/cmd/manager/main.go
> Remove ServiceMonitor in favor of Route for external scraping

- Gopkg.lock
- cmd/manager/main.go
- pkg/localmetrics/localmetrics.go
- vendor/github.com/openshift/operator-custom-metrics/LICENSE
- vendor/github.com/openshift/operator-custom-metrics/example/example.go
- vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
- vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
- vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
- vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Replaces pkg/metrics/service.go with using github.com/openshift/operator-custom-metrics pkg to register and expose metrics.
> using operator-custom-metrics library

- pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
- pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
https://jira.coreos.com/browse/SREP-1572
Refactored delete to a separate deleteDMS function and trigger it from both CD delete and the noalerts label being set.  It checks the finalizer first and bails if there is no finalizer so should be lightweight.
> Remove SyncSet if noalerts label is added

- config/config.go
- pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
- pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
- pkg/utils/utils.go
As requested in https://jira.coreos.com/browse/SREP-1831
And discussed with @wanghaoran1988 , he suggested that we should do the clean up things manually on the running clusters.
> use pre-created secret instead of embed in syncset

- README.md
The YAML in the readme did not have correct indentation.
> Fix indentation of yaml in README

- cmd/manager/main.go
- go.mod
The `operator-sdk` was updated in a separate PR #65 which broke the metrics which were introduced in #67 due a conflict between the metrics served by the `controller-runtime` and `operator-custom-metrics`. Since we don't use the runtime metrics I have just disabled them.
Also `go mod tidy`
/assign @jewzaam @jharrington22 
/cc @2uasimojo
> Disable the controller runtime metrics

- go.mod
- pkg/dmsclient/dmsclient.go
- pkg/localmetrics/localmetrics.go
- pkg/utils/clientwrapper.go
Following on from [closing comments](https://github.com/openshift/deadmanssnitch-operator/pull/67#pullrequestreview-456669366) on #67:
- Remove unused `MetricsCollector.collectors`.
- Make metrics observers consistent in naming (`Observe*`) and how they accept the duration parameter (`duration float64`).
- Corrects comments about double-counting errors.
> Aesthetic cleanup

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller_test.go
- pkg/utils/utils.go
When a ClusterDeployment is deleting, no matter what the label set, if the finalizer matches an active DMSI, remove the finalizer and clean up.
fixes [OSD-5477](https://issues.redhat.com/browse/OSD-5477)
> Clean up all DMS snitches when cluster is deleting

- hack/app_sre_create_image_catalog.sh
Builds on internal CI are failing, we're not allowed to pull the image anymore.
> Move to mirrored yq image

- Makefile
- deploy/crds/deadmanssnitch.managed.openshift.io_deadmanssnitchintegrations_crd.yaml
- hack/crd_fixup.sh
- pkg/apis/deadmanssnitch/v1alpha1/deadmanssnitchintegration_types.go
Due to an OLM bug in OCP 3.11, the generated CRD needs some tweaking. Previously this was being done via a bespoke script invoked through a go:generate directive. After boilerplate adoption, this script was doing `operator-sdk generate` redundantly (it was already part of the `op-generate` target).
This commit removes the script and the redundant `operator-sdk generate`s, and adds a temporary `make` target to do the CRD fixup. All of this will go away once we no longer need to run on 3.11.
> Move CRD fixup hack for 3.11

- build/Dockerfile
The operator binary doesn't need to run in the origin image. Use ubi-minimal to cut down on the deploy image size.
> Use ubi-minimal for second stage operator image

- README.md
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
Refactor
This PR changes the logic of the `deadmanssnitch-operator` to perform a `Patch()` of the `clusterdeployment` CR when adding or removing finalizers, rather than an `Update()`, in order to eliminate the possibility that the `Update()` call will drop data from the CR.
This PR also updates the `README` documentation to include "getting started" steps for local development, based on the very similar `pagerduty-operator`.
Some minor other nits are also addressed (spelling errors, and bad usage of `logger.Info()`)
[OSD-6070](https://issues.redhat.com/browse/OSD-6070)
I've tested this with a local deployment of `deadmanssnitch-operator` and verified that finalizers are still created and removed as expected. I have also verified that - if the Hive `clusterdeployment` CRD introduces a new …
> OSD-6070 Patch clusterdeployment instead of update

- hack/olm-registry/olm-artifacts-template.yaml
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller_test.go
Adds additional "managed.openshift.com/fake" annotation to skip.
Fixes logic when there are multiple annotations to skip.
> OSD-7196 Disable DMS for "fake" OSD clusters

- deploy/operator.yaml
- hack/olm-registry/olm-artifacts-template.yaml
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
This PR adds a deployment parameter to the OLM template so that AppSRE can deploy the operator in different govcloud vs. non-govcloud environments.
> OSD-9238 Added var for Fedramp

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller_test.go
We can now rely on the ClusterDeployment Status field `PowerState` to determine if a cluster is running or not, this field was introduced in https://github.com/openshift/hive/pull/1604
We only check legacy conditions if that field doesn't exist which may be because the running version of Hive does not yet contain support for that field. 
We are removing checking legacy Hibernation condition reason `Resuming` because during that state the cluster is not "Running" and may not check in with Deadmanssnitch causing erroneous alerts.
[OSD-9349](https://issues.redhat.com/browse/OSD-9349)
> Attempt to verify PowerState before checking legacy conditions

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
Made refactor changes suggested by @cblecker  to the operators code when checking for the presence of the FEDRAMP env variable
> OSD-9238 Refactor code for fedramp variable check on reconciler

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
Logr uses a constant message and then a key value pair, the current implementation of the `Info()` messages for the FedRAMP var cause an error on every reconcile.
```
{"level":"dpanic","ts":1642711642.4362042,"logger":"controller_deadmanssnitchintegration","msg":"odd number of arguments passed as key-value pairs for logging","Request.Namespace":"deadmanssnitch-operator","Request.Name":"osd","ignored key":false,"stacktrace":"github.com/go-logr/zapr.handleFields\n\tpkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:100\ngithub.com/go-logr/zapr.(*zapLogger).Info\n\tpkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:127\ngithub.com/openshift/deadmanssnitch-operator/pkg/controller/deadmanssnitchintegration.(*ReconcileDeadmansSnitchIntegration).Reconcile\n\tsrc/github.com/openshift/deadmanssnitch-operat …
```
> Logr uses constant messages and key value pairs, no string formatting

- cmd/manager/main.go
- config/config.go
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
Currently the fedramp variable value is not being check, causing log messages reading fedramp=true no matter what. PR ensures that:
- Log message reads fedramp only when fedramp=true
- Only check once at operator start up, instead of every reconcile loop for every clusterDeployment
Tested on stage cluster.
> Improve Fedramp Implementation

- hack/olm-registry/olm-artifacts-template.yaml
In reference to [OSD-10026](https://issues.redhat.com/browse/OSD-10026)
PR for updating the DeadMansSnitch integration to delete a DMS service if the cluster is in limited support and hence, 
**To not page SRE**
> OSD-10026 : Update DMSI to not alert for 'limited-support' clusters

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
When creating new snitches if in fedRAMP mode anonymize by using the clusterID instead of the clusterName
> Anonymize dms to use clusterID

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
Refactor
- Addons now wait for both the PagerDuty and DMS secrets to be available in the openshift-monitoring namespace before considering themselves ready. Addons now wait the extra 10-30 minutes after install for CVO to stop transitioning hence this extra delay sets off a timeout set by the Addon's team to trigger the Addon as a failed install.
- This PR ensures that DMS secrets are created on cluster installation without having to wait for ClusterOperators to transition to Ready state.
- This further ensures consistency with PagerDuty operator as pd-secrets are being created on cluster install.
- DMS resources are deleted when a cluster is Hibernating.
- Going by the JIRA, it is agreed that the check for ClusterOperators status for resuming cluster is good idea rather than checking COs …
> Create DMS secrets on cluster install

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller_test.go
Hive has been updated in all environments past the point where the PowerState field has been introduced.
This PR removes the code that handled the old ClusterDeployments.
> OSD-9447: removed code for legacy ClusterDeployments

- pkg/controller/deadmanssnitchintegration/deadmanssnitchintegration_controller.go
The backticks were escaping the newline character and causing a plain `\n` to be printed instead of an intended newline
> OSD-11272 Unescape newline character

- deploy/operator.yaml
Currently the pod is getting CPU throttled and OOM killed in production, so bumping these up for observation. Can potentially be tuned lower afterwards
```bash
❯ oc adm top po -n deadmanssnitch-operator
NAME                                       CPU(cores)   MEMORY(bytes)
deadmanssnitch-operator-5b9599dd65-5sljc   75m          791Mi
```
> OSD-11299 Remove CPU limits and increase Memory limits to 2G

- hack/olm-registry/olm-artifacts-template.yaml
revert 9a1a9278f8b40339092d937046935737705d7964 to watch clusterdeployments with limited-support label with configuration anomaly detection
for [OSD-12958](https://issues.redhat.com//browse/OSD-12958)
> enable limited support integration with configuration anomoly detector

- hack/olm-registry/olm-artifacts-template.yaml
tl;dr reverts #146 
[OSD-12958](https://issues.redhat.com//browse/OSD-12958) We noticed a bug when rolling this out to production as CAD does not take into account previous (unrelated) limited support reasons. Since it's near the end of year change freeze, rolling back this change for now to investigate later
> Revert monitoring limited support clusterdeployments

- hack/olm-registry/olm-artifacts-template.fedramp.yaml
- hack/olm-registry/olm-artifacts-template.yaml
We are in the process of removing DMS from FedRAMP. This is the first of a few PRs that will occur over the next few months. This phase will remove DMS from all non-production FedRAMP clusters while production clusters will remain active with DMS. We will target this new template for fedramp. Once we have fully transitioned from PD/DMS, this template will be removed.
> OSD-18468 - template for fedramp removal

- build/Dockerfile
- build/Dockerfile.olm-registry
- hack/olm-registry/olm-artifacts-template.yaml
This is a followup of the recent refactor done in configuration-anomaly-detection (https://github.com/openshift/configuration-anomaly-detection/pull/246).
With the most recent CAD refactor, we no longer need [the workaround](https://github.com/openshift/deadmanssnitch-operator/pull/149) to handle "resolving" pagerduty alerts, thus don't need to route alerts for clusters that are in limited support through CAD. Therefore, we can disable the snitches for clusters that are in limited support. However, with the recent addition of support exceptions, we still need to handle alerts regardless of the cluster's support state.
This PR disables snitches for clusters that are in limited support **unless they have a support exception**, thus allowing a full transparent flow for CAD. 
Tested scenarios …
> OSD-19710: no snitch for limited support clusters unless supportex

- build/Dockerfile
- build/Dockerfile.olm-registry
Looks like Quay's vulnerability scanner has the latest commit stuck in a queue. ~When this has happened in the past, a dummy commit solved things.~ edit: had to bump ubi-minimal version to pass validation test, so this PR is no longer purely dummy
> Bumping ubi-minimal to push through quay.io scan

- .github/renovate.json
- .tekton/OWNERS
- .tekton/deadmanssnitch-operator-pull-request.yaml
- .tekton/deadmanssnitch-operator-push.yaml
- build/Dockerfile
- build/Dockerfile.olm-registry
What is being added?
Adding Konflux .tekton pipelines for push and pull events
Adding Konflux .tekton build trigger expression
Adding renovate config file that is configured to auto merge bumps to the .tekton pipelines (Konflux build)
Checklist before requesting review
I have tested this locally
I have included unit tests
I have updated any corresponding documentation
Steps To Manually Test
Make sure the automated PR's created(open state) for .tekton pipelines (Konflux build)
verify the image released under konflux
https://konflux-ui.apps.kflux-prd-rh03.nnv1.p1.openshiftapps.com/ns/deadmanssnitch-operator-tenant/applications/deadmanssnitch-operator/releases
Ref https://issues.redhat.com/browse/OSD-30851
> OSD-30851 Adding konflux build files,owner and renovate config changes

- .github/dependabot.yml
https://issues.redhat.com/browse/SREP-811
---
Updates `dependabot.yml`'s `ignore` block to omit boilerplate images from auto-updating
> SREP-811 - Ensure dependabot does not attempt to update boilerplate images
